version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout
      - run:
          name: Check if HTML exists
          command: |
            if [ -f index.html ]; then
              echo "index.html found!"
            else
              echo "index.html not found!"
              exit 1
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
