version: 2.1

jobs:
  html_lint:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run HTML Linter
          command: npm run lint

workflows:
  version: 2
  validate_html:
    jobs:
      - html_lint
